INSERT INTO PLAYER (ID, USERNAME, EMAIL, PASSWORD_HASH, X, Y, GOLD, ENERGY, CURRENT_DAY) 
VALUES (1, 'Captain_Bora', 'bora@example.com', 'hash_12345', 10, 20, 100, 50, 1);
INSERT INTO EVENT (ID, NAME, DESCRIPTION, MIN_GOLD_PENALTY, MAX_GOLD_PENALTY)
VALUES (1, 'Напад розбійників', 'На ваш табір напали розбійники під покровом ночі.', 5, 10);
INSERT INTO EVENT (ID, NAME, DESCRIPTION, MIN_GOLD_PENALTY, MAX_GOLD_PENALTY)
VALUES (2, 'Напада диких тварин', 'Ваш табір атакували дикі тварини, які шукають їжу.', 1, 5);
INSERT INTO EVENT (ID, NAME, DESCRIPTION, MIN_GOLD_PENALTY, MAX_GOLD_PENALTY)
VALUES (3, 'Злива', 'Під час сильної зливи ваш табір був затоплений, і частина золота була втрачена.', 1, 2);
INSERT INTO PLAYER_EVENT_HISTORY (ID, PLAYER_ID, EVENT_ID, OCCURRED_AT)
VALUES (1, 1, 1, '2024-06-01 12:00:00');
INSERT INTO PLAYER_EVENT_HISTORY (ID, PLAYER_ID, EVENT_ID, OCCURRED_AT)
VALUES (2, 1, 2, '2024-06-02 15:30:00');
INSERT INTO PLAYER_EVENT_HISTORY (ID, PLAYER_ID, EVENT_ID, OCCURRED_AT)
VALUES (3, 1, 3, '2024-06-03 18:45:00');
INSERT INTO MAP_TILE (X, Y, TERRAIN_TYPE) VALUES (10, 20, 'Water');
INSERT INTO MAP_TILE (X, Y, TERRAIN_TYPE) VALUES (11, 20, 'Mountain');
INSERT INTO MAP_TILE (X, Y, TERRAIN_TYPE) VALUES (10, 21, 'Forest');
INSERT INTO TREASURE (ID, X, Y, MIN_GOLD, MAX_GOLD, IS_COLLECTED) VALUES (1, 10, 21, 50, 100, FALSE);
INSERT INTO TREASURE (ID, X, Y, MIN_GOLD, MAX_GOLD, IS_COLLECTED) VALUES (2, 11, 20, 30, 60, TRUE);
INSERT INTO ACTION_LOG (ID, PLAYER_ID, ACTION_TYPE, FROM_X, FROM_Y, TO_X, TO_Y, IS_VALID, CREATED_AT) 
VALUES (1, 1, 'MOVE', 10, 20, 10, 21, TRUE, '2024-06-01 12:05:00');
INSERT INTO ACTION_LOG (ID, PLAYER_ID, ACTION_TYPE, FROM_X, FROM_Y, TO_X, TO_Y, IS_VALID, CREATED_AT) 
VALUES (2, 1, 'MOVE', 10, 21, 11, 20, TRUE, '2024-06-01 12:10:00');
INSERT INTO ACTION_LOG (ID, PLAYER_ID, ACTION_TYPE, FROM_X, FROM_Y, TO_X, TO_Y, IS_VALID, CREATED_AT) 
VALUES (3, 1, 'MOVE', 11, 20, 10, 20, FALSE, '2024-06-01 12:15:00');
